In [ ]:
import os
import numpy as np
import pandas as pd
import pickle
import json
from os import path
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

os.makedirs('results/img/', exist_ok=True)
np.random.seed(1234)

project_root = Path(path.join(os.getcwd(), '../')).resolve().as_posix()
project_root

'C:/Users/omers/CodeProjects/learning-tsp'

In [3]:

results = pickle.load(
    open(f'{project_root}/results/tsp10-200_cnocorde_with_a_100.2/tsp10-200_cnocorde_with_a_100.2n25600-farthest_insertion.txt.pkl', 'rb')
)

costs, gt_costs, tours, gt_tours, opt_gap, durations = zip(*results)

pd.DataFrame({
    'cost': costs,
    'gt_cost': gt_costs,
    'opt_gap': opt_gap,
})

              cost      gt_cost    opt_gap
0       266.819516   313.724365 -14.950974
1       257.351467   270.217041  -4.761200
2       314.186246   384.441101 -18.274543
3       314.129685   317.375610  -1.022739
4       302.030017   323.490173  -6.633944
...            ...          ...        ...
25595  1145.697630  1491.932373 -23.207134
25596  1145.882174  1521.378052 -24.681300
25597  1186.278404  1629.356079 -27.193422
25598  1159.880999  1475.229614 -21.376239
25599  1189.548008  1542.451050 -22.879367

[25600 rows x 3 columns]

In [4]:

results = pickle.load(
    open(f'{project_root}/results/tsp10-200_concorde/tsp10-200_concorden25600-farthest_insertion.txt.pkl', 'rb')
)

costs, gt_costs, tours, gt_tours, opt_gap, durations = zip(*results)

pd.DataFrame({
    'cost': costs,
    'gt_cost': gt_costs,
    'opt_gap': opt_gap,
})

            cost    gt_cost       opt_gap
0       2.761457   2.761457  5.613830e-06
1       2.858019   2.858019 -3.840629e-06
2       3.288704   3.288704 -6.085341e-07
3       2.780503   2.780503  3.631136e-06
4       2.681191   2.688265 -2.631587e-01
...          ...        ...           ...
25595  11.644383  10.687936  8.948847e+00
25596  11.572681  10.624868  8.920701e+00
25597  12.216437  11.219511  8.885643e+00
25598  11.795282  11.124531  6.029481e+00
25599  11.409348  10.313395  1.062650e+01

[25600 rows x 3 columns]

In [5]:

results = pickle.load(
    open(f'{project_root}/results/tsp10-200_cnocorde_with_a_100.2/tsp10-200_cnocorde_with_a_100.2-tspsl_20-50_sl-ar-var-20pnn-gnn-max_20200308T172931-greedy-t1-0-25600.txt.pkl', 'rb')
)

costs, gt_costs, tours, gt_tours, opt_gap, durations = zip(*results)

pd.DataFrame({
    'cost': costs,
    'gt_cost': gt_costs,
    'opt_gap': opt_gap,
})

              cost      gt_cost     opt_gap
0       431.011261   313.724365   37.385334
1       477.278473   270.217041   76.627823
2       487.847717   384.441101   26.897907
3       498.589172   317.375610   57.097507
4       488.674530   323.490173   51.063179
...            ...          ...         ...
25595  8887.814453  1491.932373  495.725006
25596  8839.313477  1521.378052  481.007050
25597  9231.519531  1629.356079  466.574707
25598  9813.975586  1475.229614  565.250732
25599  8960.555664  1542.451050  480.929657

[25600 rows x 3 columns]

In [6]:

results = pickle.load(
    open(f'{project_root}/results/tsp10-200_concorde/tsp10-200_concorde-tspsl_20-50_sl-ar-var-20pnn-gnn-max_20200308T172931-greedy-t1-0-25600.txt.pkl', 'rb')
)

costs, gt_costs, tours, gt_tours, opt_gap, durations = zip(*results)

pd.DataFrame({
    'cost': costs,
    'gt_cost': gt_costs,
    'opt_gap': opt_gap,
})

            cost    gt_cost    opt_gap
0       2.761457   2.761457   0.000012
1       2.858019   2.858019  -0.000006
2       3.568250   3.288704   8.500195
3       2.783466   2.780503   0.106585
4       2.753229   2.688265   2.416575
...          ...        ...        ...
25595  12.597929  10.687936  17.870558
25596  12.182378  10.624868  14.659095
25597  13.526337  11.219511  20.560837
25598  13.010996  11.124531  16.957701
25599  13.114316  10.313395  27.158092

[25600 rows x 3 columns]